### ISSUE TITLE
BN.1 - Spike diversity (multiple lineages issue)

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1213]
- [x] Now designated **BN.1.1** S:S494P 10 sequences  GISAID query: Spike_S494P,Spike_K356T, Spike_F490S, Spike_R346T   proposed in #1176
- [x]  BN.1.1.1 S:N185D 7 Sequences.  Gisaid query:  Spike_N185D, Spike_K356T, Spike_F490S, Spike_R346T   
- [x] BN.1.2.1 S:T470N (+Orf1b:K1671I)  14 Sequences Gisaid Query :  Spike_T470N , Spike_K356T, Spike_F490S, Spike_R346T  UK #1238 
- [x] BN.1.8  S:A475V 7 (4x from Iceland) Spike_A475V,Spike_K356T, Spike_F490S, Spike_R346T
- [ ] S:V483L  3 Sequences Gisaid Query : Spike_V483L, Spike_K356T, Spike_F490S, Spike_R346T
- [ ] S:486S 4 sequence UK Spike_F486S, Spike_K356T, Spike_F490S, Spike_R346T      #1235
- [ ] S:K444R  2 sequences    GISAID query: Spike_K444R,Spike_K356T, Spike_F490S, Spike_R346T 
- [ ] S:V445F 3 Sequences UK Gisaid Query:   Spike_V445F, Spike_K356T, Spike_F490S, Spike_R346T 
- [ ] S:S94T 6 sequences UK Spike_S94T, Spike_K356T, Spike_F490S, Spike_R346T 
- [ ] S:D1139H **41 seqs** Spike_D1139H,Spike_K356T, Spike_F490S, Spike_R346T
- [ ] Spike_I434V,Spike_K356T, Spike_F490S, Spike_R346T 2 seqs 
- [ ] Spike_I934V 3 seqs Germany
- [ ] Spike_N481K 4 seqs USa Israel Uk Bn.1.5 **NEW**
- [ ] Spike_T500A 1 seq England BN.1.4
- [ ] Spike_Y266C 1 seq BN.1.3

**Comment by ryhisner** [comment]
I'm not sure if there's a possibility this was a sequencing error, but there were six BN.1 sequences today and one yesterday from England with S:S94T. 
EPI_ISL_15344575, EPI_ISL_15366263, EPI_ISL_15366276,
EPI_ISL_15366361, EPI_ISL_15366388, EPI_ISL_15366430,
EPI_ISL_15366436

**Comment by FedeGueli** [comment]
Spike_N481K going on popping up in BN. sublineages trying to see if any worth a proposal

**Comment by FedeGueli** [comment]
Spotted a minilineage of BN.1.3 with S:A688V 
EPI_ISL_15628339, EPI_ISL_16042119, EPI_ISL_16200127,
EPI_ISL_16219031, EPI_ISL_16254115, EPI_ISL_16302145,
