### ISSUE TITLE
BA.2.75* diversity to watch and designate as soon as phylogeny is clear

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#961]
There is quite a lot of relevant Spike diversity in BA.2.75* that we should try to get designated as soon as the phylogeny is clear.

I'm opening this issue to have one place to coordinate these and tick them off as we progress.

The following are known spike mutations of interest that have occurred multiple times in multiple countries in BA.2.75*

- [x] S:574V - Designated as BA.2.75.1 in #856 
- [x] S:346T on top of BA.2.75: #918
- [x] S:346T on top of BA.2.75.1: #944 #963
- [x] S:356T #947
- [x] S:452R #935
- [x] S:486S (occurs at least sometimes together with S:346T) #957 #918 #963
- [ ] S:490S (occurs at least sometimes together with S:346T and/or S:486S) #918
- [ ] S:519Q
- [ ] S:677H 
- [ ] S:E583D in BA.2.75.1 in Denmark (89seq)
- [ ] S:S939F in BA.2.75.1 in Austria, Australia, India (7 seq)

I'll try to link existing issues that discuss the above mutations above. These mutations may have already occurred multiple times independently and/or in a correlated fashion so it's not too easy to sort this out all at one unfortunately.

**Comment by FedeGueli** [comment]
Thx @corneliusroemer great work i think when epi-conditions change quickly this kind of multiple issues are very useful.
My suggestion is to wait a bit before start designating fast sublineages unless they corresponds to branches starting directly from the politomy. Soon we will see which are the successful branches and where (and if) they are geo located

**Comment by alurqu** [comment]
I built an UShER tree based around a few BA.2.75+ORF1a:3959A GenBank samples.  UShER put that into 2 different branches from BA.2.75.  But just in case others may find it helpful in finding BA.2.75 sublineages, here's the link to the interactive tree: https://nextstrain.org/fetch/github.com/alurqu/pango-designation-support-alurqu/raw/main/subtreeAuspice1_BA.2.75_20220818.json?c=gt-S_574&label=nuc%20mutations:C4586T,A22001G.  I've set the initial coloring to highlight the BA.2.75.1 S:D574V mutation.

Of course, as more data comes in the UShER tree may evolve and shift.  Please note that I did include the date in the file name, so I plan for this tree should remain as a record of the UShER tree produced today.  As the tree evolves with new data, it may be appropriate to post new version of the tree.

**Comment by corneliusroemer** [comment]
We've figured BA.2.75 out now, so this can be closed.
